---
title: "app_working"
author: "Sophie Gunn"
date: "March 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data(mtcars)
pairs <- combn(colnames(mtcars), 2)
pairs_list <- split(pairs, rep(1:ncol(pairs), each = nrow(pairs)))

scag_fun <- function(dataset, col_names){
  scagnostics <- scagnostics(dataset[col_names])
  return(scagnostics[1:9])
}
string_fun <- function(col_names){
  return(paste(col_names[1], 'vs', col_names[2]))
}

output <- t(as.data.frame(lapply(pairs_list, scag_fun, dataset = mtcars))) 
rownames(output) <- lapply(pairs_list, string_fun)
colnames(output) <- c("scag_num_1", "scag_num_2", "scag_num_3", "scag_num_4", "scag_num_5", "scag_num_6", "scag_num_7", "scag_num_8", "scag_num_9")


preds <- predict(scag_randomForest, newdata = output)
as.data.frame(preds)

df <- airquality
df <- mtcars
colnames <- vector()
    for (var in colnames(df)){
      print(var)
      print(length(unique(df[,var]))/length(df[,var]))
      if (length(unique(df[,var]))/length(df[,var]) > 0.1){
        colnames <- c(colnames, var)
      }
    }

```

looking at birthwt data:

```{r}
data(birthwt)
names(birthwt)

plot(birthwt[,c(2,3)])
plot(birthwt_1[,2], birthwt_1[, 3])
birthwt_1 <- birthwt[birthwt$age < 45,]
plot(scale(birthwt_1[,c(2,3)]))
model_1 <- lm(lwt ~ age, data = birthwt_1)
summary(model_1) #is null according to our model
plot(fitted(model_1), rstudent(model_1))

influencePlot(model_1)
cooks.distance(model_1)

plot(scale(birthwt[,c(2,10)]))
model_2 <- lm(bwt ~ age, data = birthwt)
summary(model_2)

plot(scale(birthwt[,c(3,10)]))
model_3 <- lm(bwt ~ lwt, data = birthwt)
summary(model_3)
plot(fitted(model_3), rstudent(model_3))
library(car)

colnames <- vector()
    for (var in colnames(df())){
      if (length(unique(df()[,var]))/length(df()[,var]) > 0.1){
        colnames <- c(colnames, var)
      }
    }



  #discrete_cols <- reactive({
  #  df <- df()
  #  cols <- vector()
  #  for (var in colnames(df)){
   #   if (length(unique(df[,var]))/length(df[,var]) > 0.05){
    #    cols <- c(cols, var)
     # }
    #}
    #cols
  #})
  
```