---
title: "choosing_lineups_for_study"
author: "Sophie Gunn"
date: "April 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nullabor)
library(ggplot2)
library(dplyr)
library(scagnostics)
library(MASS)
library(tidyverse)
library(caret)
library(randomForest)
```

```{r}
scagnostics16 <- read.csv("simulation_data/turk16_scagnostics.csv")
scagnostics16 <- scagnostics16[,-1]
info16 <- read.csv("simulation_data/turk16_info.csv")
info16 <- info16[,-1]
plots16 <- read.csv("simulation_data/turk16_plots.csv")
plots16 <- plots16[,-1]

scagnostics16$set <- info16$set
```


```{r}
choice <- 19
choice_plots <- subset(plots16, plots16$set == choice)
choice_info <- subset(info16, info16$set == choice)
cat(subset(choice_info, choice_info$signal == 1)$in.lineup.ID)

#To scale all plots, scales = "free" in facet_wrap
ggplot(choice_plots, aes(x, y)) +
  geom_point() +
  facet_wrap(~in.lineup.ID, nrow = 4, labeller = label_context)
```


```{r}
scagnostics18 <- read.csv("simulation_data/turk18_scagnostics.csv")
scagnostics18 <- scagnostics18[,-1]
info18 <- read.csv("simulation_data/turk18_info.csv")
info18 <- info18[,-1]
plots18 <- read.csv("simulation_data/turk18_plots.csv")
plots18 <- plots18[,-1]

scagnostics18$set <- info18$set
```


```{r}
choice <- 14
choice_plots <- subset(plots18, plots18$set == choice)
choice_info <- subset(info18, info18$set == choice)
cat(subset(choice_info, choice_info$signal == 1)$in.lineup.ID)

#To scale all plots, scales = "free" in facet_wrap
ggplot(choice_plots, aes(x, y)) +
  geom_point() +
  facet_wrap(~in.lineup.ID, nrow = 4, labeller = label_context)


```

