---
title: "working with combined"
author: "Sophie Gunn"
date: "February 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(MASS)
library(tidyverse)
library(class)
library(randomForest)
library(tidyr)
library(scagnostics)
library(caret)
library(boot)
library(e1071)
```

```{r}
data <- read.csv('command_files/combined_scagnostics.csv')

```

SVM:
```{r}
svm.1 <- svm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data)

train_ind <- sample(seq_len(nrow(data)), size = 20000)
train <- data[train_ind, ]
test <- data[-train_ind, ] 

summary(svm.1)
svm.2 <- svm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = train)


new <- predict(svm.2, test, decision.values = TRUE, probability = TRUE)

svm.probs <- predict(svm.2,type="response")

test$svm.probs <- new

test$svm.preds <- ifelse(new < .5, 0, 1)

mean(test$signal == test$svm.preds)




```