---
title: "KNN Model"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(ISLR)
library(class)

#####
#Testing Lab in Chapter 4
#####

data("Smarket")
train <- (Smarket$Year < 2005)
smarket.2005 <- Smarket[!train,]
direction.2005 <- Smarket$Direction[!train]

train.x <- cbind(Smarket$Lag1, Smarket$Lag2)[train,]
test.x <- cbind(Smarket$Lag1, Smarket$Lag2)[!train,]
train.direction <- Smarket$Direction[train]


knn.pred <- knn(train.x, test.x, train.direction, k=3)
table(knn.pred, direction.2005)

compare <- as.data.frame(cbind(direction.2005, knn.pred))
compare$correct  <- ifelse(compare$direction.2005 == compare$knn.pred, 1, 0)

sum(compare$correct)/length(compare$correct)
```

```{r}
library(tidyverse)

linear_wide_scagnostics <- read_csv("~/Desktop/comps17_18/simulation_data/linear_wide_scagnostics.csv")

error = numeric(5)

train_data_index <- sample.int(2500, 2000)
train_data <- linear_wide_scagnostics %>% filter(ID %in% train_data_index)
test_data <- linear_wide_scagnostics %>% filter(!ID %in% train_data_index)

knn.predict <- knn(train_data[,4:12], test_data[,4:12], train_data$signal, k = 3)
predict_table <- table(knn.predict, test_data$signal)

error[i] <- (predict_table[1,1]+predict_table[2,2])/sum(predict_table)

```

