---
title: "Comps2017-2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting started with GitHub

GitHub is a web-based Git repository hosting system.

* Go to GitHub, create an account (I recommend using your @carleton email), and verify your email.
* Email me your username so that I can add you to the GitHub repo
* Edit your profile (think of GitHub as an online portfolio)
* I will email you once you are added to the github repo. Clone the repo once you recieve this email by following the below steps:
    + In RStudio go to `File -> New Project`
    + Select `Version Control`
    + Select `Git`
    + The Repository URL is `https://github.com/aloy/comps17_18`; select where on your computer you want to save the files; and click `Create Project`
    
For extra help with git (e.g. for installation help) or GitHub, I recommend looking through [Happy Git and GitHub for the useR](http://happygitwithr.com/) by Jenny Bryan. You can also ask me questions.



