---
title: "AllData_knn"
author: "Aidan Mullan"
date: "2/25/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(scagnostics)
library(caret)
library(boot)
library(MASS)
library(e1071)
library(randomForest)
library(kernlab)
```

```{r}
data <- read_csv("simulation_data/combined_scagnostics.csv")

TS_control <- trainControl(method = "cv", number = 10, classProbs = TRUE)

TS_knn <- train(make.names(as.factor(signal))~.-ID, data = data, method = "knn", trControl = TS_control, tuneGrid = expand.grid(k = 1:25), metric = "Accuracy")
TS_knn

tc <- tune.control(cross = 10)
test <- tune.knn(y = as.factor(data$signal), x = data$scag_num_1+data$scag_num_2+data$scag_num_3+data$scag_num_4+data$scag_num_5+data$scag_num_6+data$scag_num_7+data$scag_num_8+data$scag_num_9, tunecontrol = tc, k = 1:25)
```

```{r}
all_LDA <- train(make.names(as.factor(signal))~.-ID, data = data, method = "lda", trControl = TS_control)
all_QDA <- train(make.names(as.factor(signal))~.-ID, data = data, method = "qda", trControl = TS_control)
```


