---
title: "Experiment_Plots"
author: "Aidan Mullan"
date: "4/15/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nullabor)
library(ggplot2)
library(dplyr)
library(scagnostics)
library(MASS)
```

```{r}
linear_plots <- read.csv("simulation_data/linear2_plots.csv")
linear_info <- read.csv("simulation_data/linear2_info.csv")
linear_scagnostics <- read.csv("simulation_data/linear2_scagnostics.csv")
linear_scagnostics <- linear_scagnostics[,3:13]
names(linear_scagnostics)[2:10] <- c("scag_num_1", "scag_num_2", "scag_num_3", "scag_num_4", "scag_num_5", "scag_num_6", "scag_num_7", "scag_num_8", "scag_num_9")

```

```{r}
n <- sample(3:8,1)
sampN <- 300#sample(c(100,200,300,400,500), 1)
samp.info <- subset(linear_info, subset = N == sampN)
samp.scag <- subset(linear_scagnostics, subset = ID %in% samp.info$ID)

lin_signal <- subset(samp.scag, subset = signal == 1)
lin_null <- subset(samp.scag, subset = signal == 0)

lineup_signal <- sample_n(lin_signal, n)
lineup_null <- sample_n(lin_null, 20-n)
lineup_scags <- rbind(lineup_signal, lineup_null) 
lineup_scags$position <- sample(1:20, 20)
lineup_scags <- lineup_scags %>% arrange(position)

chosen_plots <- subset(linear_plots, linear_plots$ID %in% lineup_scags$ID)
lineup_plots <- merge(chosen_plots, lineup_scags[,c(1,12)],
                      by.x = "ID", by.y = "ID") %>% arrange(position)

#To scale all plots, scales = "free" in facet_wrap
ggplot(lineup_plots, aes(x, y)) +
  geom_point() +
  facet_wrap(~position, nrow = 4, labeller = label_context, scales = "free") +
  theme(axis.ticks = element_blank(), axis.text = element_blank()) + labs(x = "", y = "")


#final_scags <- rbind(final_scags, lineup_scags)

```

```{r}
#Turk16 2,5,11,15,7,10,12,14
#Turk18 3,4,6,14
t16_info <- read.csv("simulation_data/turk16_info.csv")
t16_choice_info <- subset(t16_info, t16_info$set %in% c(2,5,11,15,7,10,12,14))
t16_scagnostics <- read.csv("simulation_data/turk16_scagnostics.csv")
t16_scagnostics <- t16_scagnostics[,-1]
t16_choice_scags <- subset(t16_scagnostics, t16_scagnostics$ID %in% t16_choice_info$ID)
t16_choice_scags$position <- rep(1:20, 8)
#final_scags <- rbind(final_scags, t16_choice_scags)

t18_info <- read.csv("simulation_data/turk18_info.csv")
t18_choice_info <- subset(t18_info, t18_info$set %in% c(3,4,6,14))
t18_scagnostics <- read.csv("simulation_data/turk18_scagnostics.csv")
t18_scagnostics <- t18_scagnostics[,-1]
t18_choice_scags <- subset(t18_scagnostics, t18_scagnostics$ID %in% t18_choice_info$ID)
t18_choice_scags$position <- rep(1:20, 4)
t18_choice_scags2 <- t18_choice_scags[,-11]

final_scags <- rbind(final_scags, t18_choice_scags2)
final_scags$lineup <- rep(1:18, each = 20)
#write.csv(final_scags, "exp_linear_scagnostics.csv")
```

```{r}
study_scags <- read.csv("simulation_data/exp_linear_scagnostics.csv")
study_scags$condition_lineup <- rep(c("A1_2", "B1_1", "A1_6", "B1_4", "BN_2", "AN_2", "A1_1", "A1_3", "B1_2", "A1_4", "B1_3", "B1_5", "B1_6", "A1_5", "BN_1", "BN_3", "AN_1", "AN_3"), each = 20)

study_scags$corr_plots <- rep(c(2,20,8,8,"7,8,15","5,7,10,11,15",14,15,1,14,14,17,8,9,"3,12","2,6","14,17","6,14"), each = 20)
write.csv(study_scags, "experiment_scagnostics.csv")
```






