---
title: "linear_updated"
author: "Sophie Gunn"
date: "March 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(tidyverse)
library(class)
library(randomForest)
library(tidyr)
library(scagnostics)
library(caret)
library(boot)
library(e1071)
```

```{r}

data <- read_csv("simulation_data/scagnostics_linear2.csv")
data <- data[,-2]

names(data)[3:11] <- c("scag_num_1", "scag_num_2", "scag_num_3", "scag_num_4", "scag_num_5", "scag_num_6", "scag_num_7", "scag_num_8", "scag_num_9")
names(data)
info <- read_csv("simulation_data/info_linear2.csv")
info <- info[,-1]

```

randomForest 
```{r}
forestModel <- randomForest(as.factor(signal) ~scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data, ntree=100, importance =T)

forestModel

#choose # of trees where it flattens out?
plot(forestModel)

forestModel <- randomForest(as.factor(signal) ~scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data, ntree=100, importance =T, mtre = 3)
mean(forestModel$oob.times)
importance(forestModel)

varImpPlot(forestModel)
data %>% mutate( prediction = predict(forestModel, type="response"), 
                 probs = predict(forestModel, type="prob")[,2]) %>%
  select(signal, prediction, probs) %>% head()


predict_analysis <- data %>% 
  mutate( prediction = predict(forestModel, type="response")) %>% 
  group_by(signal, prediction) %>% 
  summarize( n = n(), mean_scag_num_1 = mean(scag_num_1), mean_scag_num_2 = mean(scag_num_2),mean_scag_num_3 = mean(scag_num_3), mean_scag_num_4 = mean(scag_num_4), mean_scag_num_5 = mean(scag_num_5), mean_scag_num_6 = mean(scag_num_6), mean_scag_num_7 = mean(scag_num_7), mean_scag_num_8 = mean(scag_num_8), mean_scag_num_9 = mean(scag_num_9))

importance(forestModel)
```

```{r}
x <- data %>% select("scag_num_1", "scag_num_2", "scag_num_3", "scag_num_4", "scag_num_5", "scag_num_6", "scag_num_7", "scag_num_8", "scag_num_9")
kmeans_out <- kmeans(x, 2)
data$cluster <- kmeans_out$cluster - 1

cluster_info <- data %>% group_by(signal) %>% summarize( mean_scag_num_1 = mean(scag_num_1), mean_scag_num_2 = mean(scag_num_2),mean_scag_num_3 = mean(scag_num_3), mean_scag_num_4 = mean(scag_num_4), mean_scag_num_5 = mean(scag_num_5), mean_scag_num_6 = mean(scag_num_6), mean_scag_num_7 = mean(scag_num_7), mean_scag_num_8 = mean(scag_num_8), mean_scag_num_9 = mean(scag_num_9))

kmeans_out
```

LOGISTIC REGRESSION:
```{r}
glmScag <- glm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data, family = "binomial")

summary(glmScag)

glm.probs <- predict(glmScag,type="response")

data$predictions <- ifelse(glm.probs < .5, 0, 1)
mean(data$signal == data$predictions)

#cross validation
1-cv.glm(data, glmScag, K=10)$delta[1]

```


svm:
```{r}
svmModel <- svm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data)
summary(svmModel)
svm.probs <- predict(svmModel,type="response")

data$svmpredictions <- ifelse(svm.probs < .5, 0, 1)
mean(data$signal == data$svmpredictions)
```