---
title: "Testing"
author: "Aidan Mullan"
date: "5/3/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, fig.height = 2, fig.width = 4}
library("mlbench")
library("igraph")
library("alphahull")
library(Sleuth3)
library(ggplot2)
library(dplyr)

data <- ex1217
x <- ex
par(mfrow=c(1,2))
hull  <- chull(x)
hull <- c(hull, hull[1])
shape <- ashape(x, alpha=0.2)
plot(x, main="Convex Hull", axes=F, pch=19, cex=0.5, xlab = "", ylab = "")
lines(x[hull, ])
box()
plot(x, main="Alpha shape", axes=F, pch=19, cex=0.5)
plot(shape, add=T, wpoints=F)
box()
graph <- graph.adjacency(as.matrix(dist(x)), weighted=TRUE)
mst   <- as.undirected(minimum.spanning.tree(graph))
idx   <- get.edges(mst, E(mst))
plot(x, main="Minimal Spanning Tree", axes=F, pch=19, cex=0.5, xlab = "", ylab = "")
for (i in seq(nrow(idx))) {
  ft <- idx[i,]
  lines(x[ft,1], x[ft,2])
}
box()
dev.off()
```

```{r}
### Retrieving plotted variables ###
df <- ex1217
df <- data.frame(Mortality = scale(df$Mortality), NOX = df$NOX)

df2 = na.omit(df) %>%
  mutate(hull = 1:n(), hull = factor(hull, chull(log(NOX), Mortality))) %>%
  arrange(hull)

### Convex Hull ###
q <- ggplot(df2, aes(log(NOX), Mortality)) +
  geom_polygon(aes(color = "raspberry"), data = filter(df2, !is.na(hull)), alpha = 0.5, fill = NA) +
  geom_point() +
  theme(legend.position = "none") + 
  ggtitle("Convex Hull")


p <- ggplot(df2, aes(log(NOX), Mortality)) + geom_point() + ggtitle("Minimal Spanning Tree") + theme(legend.position = "none", axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

### Minimum Spanning Tree ###
p <- ggplot(df2, aes(log(NOX), Mortality)) + geom_point() + ggtitle("Minimal Spanning Tree") + theme(legend.position = "none")

x <- cbind(log(df$NOX), df$Mortality)
x <- unique(x)
graph <- graph.adjacency(as.matrix(dist(x)), weighted=TRUE)
mst   <- as.undirected(minimum.spanning.tree(graph))
idx   <- get.edges(mst, E(mst))
distances <- numeric(length(idx[,1]))
for (i in seq(nrow(idx))) {
  ft <- idx[i,]
  x1 <- x[ft,1][1]; x2 <- x[ft,1][2]; y1 <- x[ft,2][1]; y2 <- x[ft,2][2]
  p <- p + geom_segment(aes(color = "raspberry"), x = x1, xend =x2 , y = y1, yend = y2)
  distances[i] <- sqrt((x2-x1)^2+(y2-y1)^2)
}
hist(distances, xlab = "Edge Lengths", main = "Distribution of MST Edge Lengths")

### Alpha Hull ###
ex = data.frame(x = log(df2$NOX), y = df2$Mortality)
ex_ashape = ashape(ex, alpha = 1.5)
ex_mat = ex_ashape$edges[, c("ind1", "ind2")] # Take the coordinates of points on the edges of the alpha shape

# Convert 'numeric' matrix to 'character' matrix, to avoid wrong node orders 
# (Otherwise 'graph.edgelist()' interprets number as order of nodes)
class(ex_mat) = "character"
ex_graph = graph.edgelist(ex_mat, directed = F) # Make the graph of points

# Cut open the graph to walk through it in order
cut_graph = ex_graph - E(ex_graph)[1]  # Cut the first edge
ends = names(which(degree(cut_graph) == 1))   # Get two nodes with degree = 1
path = get.shortest.paths(cut_graph, ends[1], ends[2])$vpath[[1]] # Compute a path
path_nodes = as.numeric(V(ex_graph)[path]$name) # Get node names (= row numbers in original data.frame)

s <- ggplot(ex, aes(x = x, y = y)) +
  geom_point() +
  geom_polygon(data = ex[path_nodes, ], aes(color = "raspberry"), alpha = 0.5, fill = NA) +
  theme(legend.position = "none") + 
  ggtitle("Alpha Hull") + 
  labs(x = "log(NOX)", y = "Mortality")
  

q
s
p

```

```{r}
library(datasauRus)
df <- subset(datasaurus_dozen, subset = dataset == "dino")

df2 <- na.omit(df) %>%
  mutate(hull = 1:n(), hull = factor(hull, chull(x, y))) %>%
  arrange(hull)

q <- ggplot(df2, aes(x, y)) +
  geom_polygon(aes(color = "raspberry"), data = filter(df2, !is.na(hull)), alpha = 0.5, fill = NA) +
  geom_point() +
  theme(legend.position = "none", axis.text = element_blank(), axis.ticks = element_blank()) + 
  ggtitle("Convex Hull") 

p <- ggplot(df2, aes(x, y)) + geom_point() + ggtitle("Minimal Spanning Tree") + theme(legend.position = "none", axis.text = element_blank(), axis.ticks = element_blank())
x <- cbind(df$x, df$y)
x <- unique(x)
graph <- graph.adjacency(as.matrix(dist(x)), weighted=TRUE)
mst   <- as.undirected(minimum.spanning.tree(graph))
idx   <- get.edges(mst, E(mst))
distances <- numeric(141)
for (i in seq(nrow(idx))) {
  ft <- idx[i,]
  x1 <- x[ft,1][1]; x2 <- x[ft,1][2]; y1 <- x[ft,2][1]; y2 <- x[ft,2][2]
  p <- p + geom_segment(aes(color = "raspberry"), x = x1, xend =x2 , y = y1, yend = y2)
  distances[i] <- sqrt((x2-x1)^2+(y2-y1)^2)
}
hist(distances)

### Alpha Hull ###
ex = data.frame(x = df2$x, y = df2$y)
ex_ashape = ashape(ex, alpha = 2)
ex_mat = ex_ashape$edges[, c("ind1", "ind2")] # Take the coordinates of points on the edges of the alpha shape

# Convert 'numeric' matrix to 'character' matrix, to avoid wrong node orders 
# (Otherwise 'graph.edgelist()' interprets number as order of nodes)
class(ex_mat) = "character"
ex_graph = graph.edgelist(ex_mat, directed = F) # Make the graph of points

# Cut open the graph to walk through it in order
cut_graph = ex_graph - E(ex_graph)[1]  # Cut the first edge
ends = names(which(degree(cut_graph) == 1))   # Get two nodes with degree = 1
path = get.shortest.paths(cut_graph, ends[1], ends[2])$vpath[[1]] # Compute a path
path_nodes = as.numeric(V(ex_graph)[path]$name) # Get node names (= row numbers in original data.frame)

s <- ggplot(ex, aes(x = x, y = y)) +
  geom_point() +
  geom_polygon(data = ex[path_nodes, ], aes(color = "raspberry"), alpha = 0.5, fill = NA) +
  theme(legend.position = "none", axis.text = element_blank(), axis.ticks = element_blank()) + 
  ggtitle("Alpha Hull") + 
  labs(x = "x", y = "y")

s
p
q


```


```{r, fig.height = 2, fig.width = 4}
library("mlbench")
library("igraph")
data <- read.csv('for_presentation/Survey.csv')
data2 <- data %>% filter(Question.15 < 4 & Question.15 > 0 ) 


x <- cbind(data2$Question.14, data2$Question.15)
x <- unique(x)
x <- na.omit(x)
svg("scagnosticsBase.svg", width=10, height=3)
par(mfrow=c(1,2))
hull  <- chull(x)
hull <- c(hull, hull[1])
plot(x, main="Convex Hull", axes=F, pch=19, cex=0.5, xlab = "", ylab = "")
lines(x[hull, ])
box()
```


#stringy scagnostic
```{r}
n <- 100
set.seed(10)
x <- rnorm(n)
y <- (x^4 + (-1)^(rbernoulli(n, p = 0.5))*rexp(n, rate = 0.8))
plot(x,y)

stringy <- data.frame(x = x, y = y)

ggplot(stringy) + 
  geom_point(aes(x = x, y = y)) + 
  theme(axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank())


p <- ggplot(stringy, aes(x = scale(x), y = scale(y))) + geom_point() + ggtitle("Minimum Spanning Tree") + theme(legend.position = "none", axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())
x <- cbind(scale(stringy$x), scale(stringy$y))
x <- unique(x)
svg("scagnosticsBase.svg", width=10, height=3)
graph <- graph.adjacency(as.matrix(dist(x)), weighted=TRUE)
mst   <- as.undirected(minimum.spanning.tree(graph))
idx   <- get.edges(mst, E(mst))
for (i in seq(nrow(idx))) {
  ft <- idx[i,]
  p <- p + geom_segment(aes(color = "raspberry"), x = x[ft,1][1], xend = x[ft,1][2], y = x[ft,2][1], yend = x[ft,2][2])
}

p
```

```{r}
### Alpha Hulls ###
### Low Convex ###
set.seed(10)
x <- rexp(100,4)
y <- rexp(100,4)
minx <- min(x)
miny <- min(y)
df <- as.data.frame(matrix(c(rep(minx,100), x, y, rep(miny,100)), nrow = 200, ncol = 2, byrow = FALSE))

ex = data.frame(x = df$V1, y = df$V2)
ex = unique(ex)
ex_ashape = ashape(ex, alpha = 0.2)
ex_mat = ex_ashape$edges[, c("ind1", "ind2")]
class(ex_mat) = "character"
ex_graph = graph.edgelist(ex_mat, directed = F) # Make the graph of points
cut_graph = ex_graph - E(ex_graph)[1]  # Cut the first edge
ends = names(which(degree(cut_graph) == 1))   # Get two nodes with degree = 1
path = get.shortest.paths(cut_graph, ends[1], ends[2])$vpath[[1]] # Compute a path
path_nodes = as.numeric(V(ex_graph)[path]$name) # Get node names (= row numbers in original data.frame)

convex.low <- ggplot(ex, aes(x = x, y = y)) +
  geom_point() +
  geom_polygon(data = ex[path_nodes, ], aes(color = "raspberry"),  alpha = 0.5, fill = NA) +
  geom_segment(aes(color = "raspberry"), x = .002643, xend = .931209 , y = .004299, yend = .004299) +
  geom_segment(aes(color = "raspberry"), x = .002643, xend = .002643 , y = .004299, yend = 1.114296) +
  theme(legend.position = "none") + 
  ggtitle("Alpha Hull") + 
  labs(x = "log(NOX)", y = "Mortality")
convex.low

### Mid Convex ###
set.seed(2)
x1 <- rexp(100,.5)
y1 <- rnorm(100,0,20)
df1 <- as.data.frame(matrix(c(x1,y1), ncol = 2, byrow = FALSE))

ex = data.frame(x = df1$V1, y = df1$V2)
ex = unique(ex)
ex_ashape = ashape(ex, alpha = 13)
ex_mat = ex_ashape$edges[, c("ind1", "ind2")]
class(ex_mat) = "character"
ex_graph = graph.edgelist(ex_mat, directed = F) # Make the graph of points
cut_graph = ex_graph - E(ex_graph)[1]  # Cut the first edge
ends = names(which(degree(cut_graph) == 1))   # Get two nodes with degree = 1
path = get.shortest.paths(cut_graph, ends[1], ends[2])$vpath[[1]] # Compute a path
path_nodes = as.numeric(V(ex_graph)[path]$name) # Get node names (= row numbers in original data.frame)

convex.med <- ggplot(ex, aes(x = x, y = y)) +
  geom_point() +
  geom_polygon(data = ex[path_nodes, ], aes(color = "raspberry"),  alpha = 0.5, fill = NA) +
  theme(legend.position = "none") + 
  ggtitle("Alpha Hull") + 
  labs(x = "log(NOX)", y = "Mortality")
convex.med

### High Convex ###
x2 <- runif(2000,0,1)
y2 <- runif(2000,0,1)
df2 <- as.data.frame(matrix(c(x2,y2), ncol = 2, byrow = FALSE))

ex = data.frame(x = df2$V1, y = df2$V2)
ex = unique(ex)
ex_ashape = ashape(ex, alpha = 0.05)
ex_mat = ex_ashape$edges[, c("ind1", "ind2")]
class(ex_mat) = "character"
ex_graph = graph.edgelist(ex_mat, directed = F) # Make the graph of points
cut_graph = ex_graph - E(ex_graph)[1]  # Cut the first edge
ends = names(which(degree(cut_graph) == 1))   # Get two nodes with degree = 1
path = get.shortest.paths(cut_graph, ends[1], ends[2])$vpath[[1]] # Compute a path
path_nodes = as.numeric(V(ex_graph)[path]$name) # Get node names (= row numbers in original data.frame)

convex.high <- ggplot(ex, aes(x = x, y = y)) +
  geom_point() +
  geom_polygon(data = ex[path_nodes, ], aes(color = "raspberry"),  alpha = 0.5, fill = NA) +
  theme(legend.position = "none") + 
  ggtitle("Alpha Hull") + 
  labs(x = "log(NOX)", y = "Mortality")
convex.high
```

