---
title: "Scagnostic_Examples"
author: "Aidan Mullan"
date: "4/5/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(scagnostics)
library(tidyverse)
library(mlbench)
library(igraph)
library(vegan)
```


```{r, fig.height=4, fig.width=5}
#Outlying
set.seed(1)
n <- 100
mu1 <- 0; mu2 <- 0
sigma <- matrix(c(1, .3, .3, 1), 2)
xy1 <- mvrnorm(n, mu = c(mu1, mu2), Sigma = sigma)
scagnostics(xy1[,1], xy1[,2])$s[1] #.0524

xy2 <- mvrnorm(10, mu = c(10,10), Sigma = sigma)
xy2 <- rbind(xy1, xy2)
scagnostics(xy2[,1], xy2[,2])$s[1] #.5430

xy3 <- mvrnorm(2, mu = c(-10,-10), Sigma = sigma)
xy4 <- mvrnorm(2, mu = c(10, -10), Sigma = sigma)
xy4 <- rbind(xy1, xy3, xy4)
scagnostics(xy4[,1], xy4[,2])$s[1] #.976

par(mfrow = c(2,2))
plot(xy1[,1], xy1[,2], main = "Outlying: .052", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(xy2[,1], xy2[,2], main = "Outlying: .543", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(xy4[,1], xy4[,2], main = "Outlying: .976", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")

#Low
ggplot(as.data.frame(xy1)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

#Medium
ggplot(as.data.frame(xy2)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

#High
ggplot(as.data.frame(xy4)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

```


```{r, fig.height=4, fig.width=5}
#Skewed
set.seed(1)
x <- rnorm(100, 5,1); y <- 4.65*x + rnorm(100, 0, 5)
x2 <- rnorm(100, 5, 1); y2 <- 0*x2 + rnorm(100, 0, 3)
xy <- data.frame(x = c(x,x2), y=c(y,y2))
scagnostics(xy$x,xy$y)$s[2] #.651


skew.plots <- read_csv("simulation_data/sparse_trend_plots.csv")
skew.test <- subset(skew.plots, skew.plots$ID == 314)
scagnostics(skew.test$x, skew.test$y)$s[2] #.382

skew.plots2 <- read_csv("simulation_data/turk16_plots.csv")
skew.test2 <- subset(skew.plots2, skew.plots2$ID == 254)
scagnostics(skew.test2$x, skew.test2$y)$s[2] #.877

par(mfrow = c(2,2))
plot(skew.test$x, skew.test$y, main = "Skewed: .382", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(xy$x,xy$y, main = "Skewed: .651", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(skew.test2$x, skew.test2$y, main = "Skewed: .877", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
```

```{r, fig.height=4, fig.width=5}
#Clumpy
set.seed(1)
sigma <- matrix(c(.1, 0, 0, .1), 2) 
c1.xy1 <- mvrnorm(100, mu = c(2,2), Sigma = sigma); c1.xy2 <- mvrnorm(100, mu = c(10,4), Sigma = sigma)
clump1.xy <- rbind(c1.xy1, c1.xy2)
scagnostics(clump1.xy[,1], clump1.xy[,2])$s[3] #.900

sigma <- matrix(c(1.3, 0, 0, 1.3), 2)
c2.xy1 <- mvrnorm(100, mu = c(0,4), Sigma = sigma); c2.xy2 <- mvrnorm(100, mu = c(4.5,4), Sigma = sigma)
c2.xy3 <- mvrnorm(100, mu = c(0,9), Sigma = sigma); c2.xy4 <- mvrnorm(100, mu = c(4.5,9), Sigma = sigma)
clump2.xy <- rbind(c2.xy1, c2.xy2, c2.xy3, c2.xy4)
scagnostics(clump2.xy[,1], clump2.xy[,2])$s[3] #.007

sigma <- matrix(c(.6, 0, 0, .6), 2)
c3.xy1 <- mvrnorm(100, mu = c(1,1), Sigma = sigma); c3.xy2 <- mvrnorm(100, mu = c(6,2), Sigma = sigma)
c3.xy3 <- mvrnorm(100, mu = c(4,6), Sigma = sigma)
clump3.xy <- rbind(c3.xy1, c3.xy2, c3.xy3)
scagnostics(clump3.xy[,1], clump3.xy[,2])$s[3]  #.446

par(mfrow = c(2,2))
plot(clump2.xy[,1], clump2.xy[,2], main = "Clumpy: .007", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(clump3.xy[,1], clump3.xy[,2], main = "Clumpy: .446", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(clump1.xy[,1], clump1.xy[,2], main = "Clumpy: .900", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
```

```{r, fig.height=4, fig.width=5}
#Sparse
```

```{r, fig.height=4, fig.width=5}
#Striated
stria.plots <- read_csv("simulation_data/striated_plots.csv")
stria1.test <- subset(stria.plots, subset = ID == 488)
scagnostics(stria1.test$x, stria1.test$y)$s[5] #.928

stria2.test <- subset(stria.plots, subset = ID == 553)
scagnostics(stria2.test$x, stria2.test$y)$s[5] #.514

stria3.test <- subset(stria.plots, subset = ID == 300)
scagnostics(stria3.test$x, stria3.test$y)$s[5]

par(mfrow = c(2,2))
plot(stria3.test$x, stria3.test$y, main = "Striated: .035", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(stria2.test$x, stria2.test$y, main = "Striated: .514", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(stria1.test$x, stria1.test$y, main = "Striated: .928", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
```

```{r, fig.height=4, fig.width=5}
#Convex

```

```{r, fig.height=4, fig.width=5}
#Skinny
```

```{r, fig.height=4, fig.width=5}
#Stringy
set.seed(1)
string1.x <- runif(200,-20,20); string1.y <- string1.x^3 + rnorm(200,0,85)
scagnostics(string1.x, string1.y)$s[8] #.894

string2.x <- runif(100,-10,10); string2.y <- string2.x^4 + rnorm(100, 0, 200)
scagnostics(string2.x, string2.y)$s[8] #.611

string3.xy <- mvrnorm(400, mu = c(0,0), Sigma = matrix(c(3,0,0,3),2))
scagnostics(string3.xy[,1], string3.xy[,2])$s[8] #.363

par(mfrow = c(2,2))
plot(string3.xy[,1], string3.xy[,2], main = "Stringy: .363", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(string2.x, string2.y, main = "Stringy: .611", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(string1.x, string1.y, main = "Stringy: .894", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")

stringy1 <- data.frame(id = 1, Stringy = "0.363", x = string3.xy[,1], y = string3.xy[,2])
stringy2 <- data.frame(id = 2, Stringy = "0.611", x = string2.x, y = string2.y)
stringy3 <- data.frame(id = 3, Stringy = "0.894", x = string1.x, y = string1.y)
stringy <- rbind(stringy1, stringy2, stringy3)

ggplot(stringy %>% filter(id == 1)) + geom_point(aes(x = x, y = y)) +
  theme(axis.line=element_blank(),
        axis.text = element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank())+
  labs(title = "Stringy = 0.363")

ggplot(stringy %>% filter(id == 2)) + geom_point(aes(x = x, y = y)) +
  theme(axis.line=element_blank(),
        axis.text = element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank())+
  labs(title = "Stringy = 0.611")

ggplot(stringy %>% filter(id == 3)) + geom_point(aes(x = x, y = y)) +
  theme(axis.line=element_blank(),
        axis.text = element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank()) +
  labs(title = "Stringy = 0.894")

#Initial Example Plot
set.seed(1)
labels <- as.factor(sample(LETTERS[1:5], 100, replace=TRUE))
dat <- mvrnorm(n=100, mu = c(1:4), Sigma=matrix(1:16, ncol=4)) + as.numeric(labels)^2
dat2 <- mvrnorm(100, mu = c(0,0), Sigma = matrix(c(3,0,0,3),2)) + as.numeric(labels)

plot(dat2)
d <- dist(dat2)
x <- spantree(d, toolong = 0)
plot(x)
plot(dat)
```

```{r, fig.height=4, fig.width=5}
#Monotonic
set.seed(1)
mono1.xy <- mvrnorm(200, mu = c(0,0), Sigma = matrix(c(2,0,0,2),2))
scagnostics(mono1.xy[,1], mono1.xy[,2])$s[9] #>.001

mono.plots <- read_csv("simulation_data/turk16_plots.csv")
mono.test <- subset(mono.plots, mono.plots$ID == 3)
scagnostics(mono.test$x, mono.test$y)$s[9] #.948

mono.plots2 <- read.csv("simulation_data/TS_Plots.csv")
mono.test2 <- subset(mono.plots2, subset = ID == 1705) 
scagnostics(mono.test2$x, mono.test2$y)$s[9] #.416

par(mfrow = c(2,2))
plot(mono1.xy[,1], mono1.xy[,2], main = "Monotonic: .001", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(mono.test2$x, mono.test2$y, main = "Monotonic: .506", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")
plot(mono.test$x, mono.test$y, main = "Monotonic: .948", xlab = "X", ylab = "Y", xaxt = "n", yaxt = "n")

#Low
ggplot(as.data.frame(xy1)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

#Medium
ggplot(as.data.frame(xy2)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())

#High
ggplot(as.data.frame(xy4)) + geom_point(aes(x = V1, y = V2)) + 
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())
```

