---
title: "sophie_eda"
author: "Sophie Gunn"
date: "February 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(scagnostics)
install.packages("randomForest")
library(randomForest)
library(tidyverse)
library(tidyr)
library(scagnostics)
donut_scagnostics <- read.csv("/Users/sophiegunn/Desktop/SchoolWork/winter/comps/comps17_18/simulation_data/donut_scagnostics.csv")

quad_scagnostics <- read.csv("/Users/sophiegunn/Desktop/School Work/winter/comps/comps17_18/simulation_data/quad_scagnostics.csv")

aggregate(donut_scagnostics, by=list(donut_scagnostics$signal), FUN=mean, na.rm=TRUE)
aggregate(quad_scagnostics, by=list(quad_scagnostics$signal), FUN=mean, na.rm=TRUE)

```

looking at donut modelling:
```{r}
training <- sample(seq(1:16000), 10000)

training_subset <- donut_scagnostics[training,]
testing_subset <- donut_scagnostics[-training,]

```
ehh, weird errors
```{r}
install.packages("arm")
library(arm)

glmScag <- bayesglm(signal ~ X1+X2+X3+X4+X5+X6+X7+X8+X9, data = training_subset)

summary(glmScag)

glm.probs <- predict(glmScag,type="response")

data$predictions <- ifelse(glm.probs < .5, 0, 1)
mean(data$signal == data$predictions)

```


```{r}
forestModel <- randomForest(as.factor(signal) ~X1+X2+X3+X4+X5+X6+X7+X8+X9, data = training_subset, ntree=100, importance =T)

yhat <- predict(forestModel, newdata = testing_subset)

probs_test <- testing_subset %>%
   transmute(model1 = predict(forestModel, newdata=testing_subset, type="response"), dataType="test", y = signal) 

conf.mat <- table(probs_test$y, probs_test$model1)
conf.mat

(conf.mat[1,1] + conf.mat[2,2])/(sum(conf.mat)) #accuracy
conf.mat[1,1]/(conf.mat[1,1] + conf.mat[2,1]) #precision
conf.mat[1,1]/(conf.mat[1,1] + conf.mat[1,2]) #sensitivity
conf.mat[2,2]/(conf.mat[2,1] + conf.mat[2,2]) #specificity

#looks really good!
```