---
title: "Cluster Simulation"
author: "Logan Crowl"
date: "2/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(readr)
library(devtools)
devtools::install_github("aloy/scagnostics")
library(scagnostics)
library(ggplot2)

```


```{r}
R <- 5 
Ns <- c(33,67,100,133,167)
startingAngle <- c(0, pi/4, pi/2, 3*pi/4, pi, 5*pi/4, 3*pi/2, 7*pi/4)
rad <- c(1,2,3,4,5)
rho <- 0

clusterPlots <- vector(mode = "list")
nullPlots <- vector(mode = "list")
info <- vector(mode = "list")
nullInfo <- vector(mode = "list")

index = 1

for(r in rad){
  S1 <- c(r/8, r/7, r/6, r/5, r/4, r/3)
  S2 <- c(r/8, r/7, r/6, r/5, r/4, r/3)
  for(theta in startingAngle){
    mu1x <- r*cos(theta)
    mu1y <- r*sin(theta)
    mu2x <- r*cos(2*pi/3 + theta) 
    mu2y <- r*sin(2*pi/3 + theta)
    mu3x <- r*cos(4*pi/3 + theta)
    mu3y <- r*sin(4*pi/3 + theta)
    mu1 <- c(mu1x,mu1y)
    mu2 <- c(mu2x,mu2y)
    mu3 <- c(mu3x,mu3y)
    for(n in Ns){
        for(s1 in S1){
          for(s2 in S2) {
            sigma <- matrix(c(s1^2, s1*s2*rho, s1*s2*rho, s2^2),2)
            xy1 <- as.data.frame(mvrnorm(n, mu = mu1, Sigma = sigma))
            xy2 <- as.data.frame(mvrnorm(n, mu = mu2, Sigma = sigma))
            xy3 <- as.data.frame(mvrnorm(n, mu = mu3, Sigma = sigma))
            xy <- rbind(xy1, xy2, xy3)
            
            nullsigma <- matrix(c(r^2, r*r*rho, r*r*rho, r^2),2)
            nullxy1 <- as.data.frame(mvrnorm(n, mu = mu1, Sigma = nullsigma))
            nullxy2 <- as.data.frame(mvrnorm(n, mu = mu2, Sigma = nullsigma))
            nullxy3 <- as.data.frame(mvrnorm(n, mu = mu3, Sigma = nullsigma))
            nullxy <- rbind(nullxy1, nullxy2, nullxy3)

            clusterPlots[[index]] <- list(ID = index,  x = xy[,1] , y = xy[,2])
            nullPlots[[index]] <- list(ID = index, x = nullxy[,1], y = nullxy[,2])
            info[[index]] <- list(ID = index, N = n, radius = r, startingAngle = theta,  sd1 = s1, sd2 = s2, signal = 1)
            nullInfo[[index]] <-list(ID = index, N = n, radius = r, startingAngle = theta,  sd1 = r, sd2 = r, signal = 0)
            index = index + 1
           }
         }
        }
      }
}
  

```


```{r}
#####
#Need to run scagnostics and compile null/signal datasets into main
#####
scagnostics1 <- vector(mode = "list")

index = 1
for (plot in clusterPlots) {
  if (index%%100 == 0){print(index)}
  scagnostics1[[index]] <- list(ID = index, scagnostics = scagnostics(plot$x, plot$y)$s, signal = 1)
  index = index + 1
}

scagnostics_null <- vector(mode = "list")

index = 1
for (plot in nullPlots) {
  if (index%%100 == 0){print(index)}
  scagnostics_null[[index]] <- list(ID = index, scagnostics = scagnostics(plot$x, plot$y)$s, signal = 0)
  index = index + 1
}

info <- rbind(info, nullInfo)
clusterPlots <- rbind(clusterPlots, nullPlots)
scagnostics1 <- rbind(scagnostics1, scagnostics_null)
```


```{r}
library(plyr)
library(tidyverse)

cluster_info_df <- ldply(info, data.frame)
cluster_scatter_df <- ldply(clusterPlots, data.frame)

cluster_scagnostics_df <- ldply(scagnostics1, data.frame)
scag_num <- rep(seq(1:9), length(cluster_scagnostics_df))
cluster_scagnostics_df$scag_num <- scag_num

  
write.csv(cluster_info_df, "Cluster_Info.csv")
write.csv(cluster_scatter_df, "Cluster_Plots.csv")
write.csv(cluster_scagnostics_df, "Cluster_Scagnostics.csv")
```




