---
title: "Logistic"
author: "Cari Comnick"
date: "2/6/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scagnostics)
library(caret)
library(boot)
```

```{r}
data <- read_csv("simulation_data/linear_trend_scagnostics.csv")
data <- data[,-1]
info <- read_csv("simulation_data/linear_trend_info.csv")
info <- info[,-1]
```

```{r}
#mark as interesting/non in info
info$signal <- ifelse(info$R == 0, 0, 1)
data <- data %>%
  left_join(info) %>%
  select(ID, scag_num, scagnostics, signal)

data <- data %>%
  spread(key = scag_num, value = scagnostics, sep = "_")

#write.csv(data, "linear_wide_scagnostics.csv")
```

```{r}
#logistic model
glmScag <- glm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = data, family = "binomial")

summary(glmScag)

glm.probs <- predict(glmScag,type="response")

data$predictions <- ifelse(glm.probs < .5, 0, 1)
mean(data$signal == data$predictions)
```

```{r}
#cross validation
1-cv.glm(data, glmScag, K=10)$delta[1]
```

```{r}
glmScag1 <- glm(signal ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_7+scag_num_8+scag_num_9, data = data, family = "binomial")
summary(glmScag1)
anova(glmScag1, test = "Chisq")
anova(glmScag1, glmScag, test = "Chisq")
#plot(glmScag1)
```

```{r}
glmScag2 <- glm(signal ~ scag_num_9, data = data, family = "binomial")
summary(glmScag1)
anova(glmScag2, glmScag, test = "Chisq")
```
