---
title: "Funnel_Simulation"
author: "Cari Comnick"
date: "2/13/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages('devtools')
#devtools::install_github("aloy/scagnostics")
```

```{r}
library(MASS)
library(readr)
library(rJava)
library(scagnostics)
library(plyr)
library(tidyverse)
```

Funnel (bivariate log-normal with rho = 0.6) from paper
Vary rhos from .4 to .9
Vary SD from .3 to 1
Center at (0,0)

For noise plots:
use r=0
```{r}
Ns <- c(100,200,300,400,500)
mu1 <- 0
mu2 <- 0
S1 <- seq(.3,1,by=.05)
mu <- c(mu1,mu2)
Rhos <- seq(.4,.9,by=.05)

scatter <- vector(mode = "list", length = length(Ns)*length(Rhos)*length(S1))
info <- vector(mode = "list", length = length(Ns)*length(Rhos)*length(S1))
index = 1

for (i in 1:5){
for(n in Ns){
  for(r in Rhos){
    for(s1 in S1){
        sigma <- matrix(c(s1^2, s1*s1*r, s1*s1*r, s1^2),2)
        xy <- mvrnorm(n, mu = mu, Sigma = sigma)
        xy <- exp(xy)
        scatter[[index]] <- list(ID = index,  x = xy[,1] , y = xy[,2])
        info[[index]] <- list(ID = index, R = r, N = n, sd = s1, interest = 1)
        index = index + 1
        
        sigma <- matrix(c(s1^2, 0, 0, s1^2),2)
        xy <- mvrnorm(n, mu = mu, Sigma = sigma)
        xy <- exp(xy)
        scatter[[index]] <- list(ID = index,  x = xy[,1] , y = xy[,2])
        info[[index]] <- list(ID = index, R = 0, N = n, sd = s1, interest = 0)
        index = index + 1
      }
    }
}
}
```

```{r}
scagnostics1 <- vector(mode = "list", length = length(Ns)*length(Rhos)*length(S1)*5)

index = 1
for (plot in scatter) {
  if (index%%100 == 0){print(index)}
  scagnostics1[[index]] <- list(ID = index, scagnostics = scagnostics(plot$x, plot$y)$s)
  index = index + 1
}

info_df <- ldply(info, data.frame)
scatter_df <- ldply(scatter, data.frame)

scagnostics_df <- ldply(scagnostics1, data.frame)
scag_num <- rep(seq(1:9), 8250)
scagnostics_df$scag_num <- scag_num
  
write.csv(info_df, "funnel_info.csv")
write.csv(scatter_df, "funnel_trend_plots.csv")
write.csv(scagnostics_df, "funnel_scagnostics.csv")
```