---
title: "Time_Series_Simulation"
author: "Aidan Mullan"
date: "2/13/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Need to work out issues of non-stationarity on non-IMA models

```{r}
library(MASS)
library(readr)
install.packages('devtools')
devtools::install_github("aloy/scagnostics")
library(scagnostics)
```

```{r}
ar_order <- c(0,1)
ma_order <- c(0,1)
i_order <- c(0,1)
ar_mag <- c(0.3, 0.5, 0.6, 0.7, 0.8, 0.9)
ma_mag <- c(0.3, 0.5, 0.6, 0.7, 0.8, 0.9)
Ns <- c(100,200,300,400,500)

TS_plot <- vector(mode = "list")
TS_info <- vector(mode = "list")
index = 1

for(n in Ns){
  for(ar in ar_order){
    for(ma in ma_order){
      for(phi in ar_mag){
        for(theta in ma_mag){
          if(ar == 0){
            if(ma == 0){
              y <- arima.sim(n = n, model = list(order = c(0,0,0)))
              TS_plot[[index]] <- list(ID = index, x = 1:n, y = as.numeric(y))
              TS_info[[index]] <- list(ID = index, n = n, ar_order = 0, ma_order = 0, i_order = i,
                                         ar_mag = 0, ma_mag = 0, signal = 0)
              index = index + 1
            }
            else{
              ma_values = sample(ma_mag, size = ma, replace = TRUE)
              y <- arima.sim(n = n, model = list(order = c(0,0,ma), ma = ma_values))
              TS_plot[[index]] <- list(ID = index, x = 1:n, y = as.numeric(y))
              TS_info[[index]] <- list(ID = index, n = n, ar_order = 0, ma_order = ma, i_order = i, 
                                       ar_mag = 0, ma_mag = ma_values, signal = 1)
              index = index + 1
            }
          }
          else{
            if(ma == 0){
              ar_values = sample(ar_mag, size = ar, replace = TRUE)
              y <- arima.sim(n = n, model = list(order = c(ar,0,0), ar = ar_values, ma = ma_values))
              TS_plot[[index]] <- list(ID = index, x = 1:n, y = as.numeric(y))
              TS_info[[index]] <- list(ID = index, n = n, ar_order = ar, ma_order = ma, i_order = i, 
                                     ar_mag = ar_values, ma_mag = ma_values, signal = 1)
              index = index + 1
            }
            else{
            ma_values = sample(ma_mag, size = ma, replace = TRUE)
            ar_values = sample(ar_mag, size = ar, replace = TRUE)
            y <- arima.sim(n = n, model = list(order = c(ar,0,ma), ar = ar_values, ma = ma_values))
            TS_plot[[index]] <- list(ID = index, x = 1:n, y = as.numeric(y))
            TS_info[[index]] <- list(ID = index, n = n, ar_order = ar, ma_order = ma, i_order = i, 
                                     ar_mag = ar_values, ma_mag = ma_values, signal = 1)
            index = index + 1
            }
          }  
        }
      }
    }
  }
}

```

```{r}
TS_scagnostics <- vector(mode = "list")

index = 1
for (plot in TS_plot) {
  if (index%%100 == 0){print(index)}
  TS_scagnostics[[index]] <- list(ID = index, scagnostics = scagnostics(plot$x, plot$y)$s)
  index = index + 1
}

```

```{r}
library(plyr)
library(tidyverse)

TS_info_df <- ldply(TS_info, data.frame)
TS_scatter_df <- ldply(TS_plot, data.frame)

TS_scagnostics_df <- ldply(TS_scagnostics, data.frame)
scag_num <- rep(seq(1:9), length(TS_scagnostics))
TS_scagnostics_df$scag_num <- scag_num
  
write.csv(TS_info_df, "TS_Info.csv")
write.csv(TS_scatter_df, "TS_Plots.csv")
write.csv(TS_scagnostics_df, "TS_Scagnostics.csv")
```