---
title: "choosing_lineups_for_study"
author: "Sophie Gunn"
date: "April 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nullabor)
library(ggplot2)
library(dplyr)
library(scagnostics)
library(MASS)
library(tidyverse)
library(caret)
library(randomForest)
```

```{r}
scagnostics16 <- read.csv("simulation_data/turk16_scagnostics.csv")
scagnostics16 <- scagnostics16[,-1]
info16 <- read.csv("simulation_data/turk16_info.csv")
info16 <- info16[,-1]
plots16 <- read.csv("simulation_data/turk16_plots.csv")
plots16 <- plots16[,-1]

scagnostics16$set <- info16$set
```
both: 16_2, 16_15
A: 
16: 5, 9, 11, 16, 19
18: 3, 4

B: 
16: 7, 10, 12, 14, 20
18: 6, 14

```{r}
#choices <- c(5, 9, 11, 16, 19, 7, 10, 12, 14, 20)
choices <- c(2, 15)
for (choice in choices){
choice_plots <- subset(plots16, plots16$set == choice)
choice_info <- subset(info16, info16$set == choice)
cat(subset(choice_info, choice_info$signal == 1)$in.lineup.ID)

ggplot(choice_plots, aes(x, y)) +
  geom_point(size = 1) +
  facet_wrap(~in.lineup.ID, nrow = 4, labeller = label_context) +  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank(), axis.ticks.y=element_blank()) 
title <- paste0('16_', choice, '.png')
ggsave(title)
}
```


```{r}
scagnostics18 <- read.csv("simulation_data/turk18_scagnostics.csv")
scagnostics18 <- scagnostics18[,-1]
info18 <- read.csv("simulation_data/turk18_info.csv")
info18 <- info18[,-1]
plots18 <- read.csv("simulation_data/turk18_plots.csv")
plots18 <- plots18[,-1]

scagnostics18$set <- info18$set
```

both: 16_2, 16_15
A: 
16: 5, 9, 11, 16, 19
18: 3, 4

B: 
16: 7, 10, 12, 14, 20
18: 6, 14
```{r}
choices <- c(3, 4, 6, 14)
for (choice in choices){
choice_plots <- subset(plots18, plots18$set == choice)
choice_info <- subset(info18, info18$set == choice)
cat(subset(choice_info, choice_info$signal == 1)$in.lineup.ID)

#To scale all plots, scales = "free" in facet_wrap
ggplot(choice_plots, aes(x, y)) +
  geom_point() +
  facet_wrap(~in.lineup.ID, nrow = 4, labeller = label_context) +  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank(), axis.ticks.y=element_blank()) 
title <- paste0('18_', choice, '.png')
ggsave(title)
}
```


