---
title: "classifying_model_type"
author: "Sophie Gunn"
date: "February 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(tidyverse)
library(class)
library(randomForest)
library(tidyr)
library(scagnostics)
library(caret)
library(boot)
library(e1071)
library(partykit)
```

```{r}
data <- read.csv('simulation_data/combined_scagnostics.csv')

```


```{r}
data$model_type <- data$model
data$model_type <- as.character(data$model_type)
data$model_type <- ifelse(data$signal == 0, "null", data$model_type) 
data$model_type_fac <- as.factor(data$model_type)


train_ind <- sample(seq_len(nrow(data)), size = 20000)
train <- data[train_ind, ]
test <- data[-train_ind, ] 

table(data$model_type)
```

```{r}
scag_rpart <- rpart(train$model_type ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = train)
plot(as.party(scag_rpart), type = "simple")

scag_randomForest <- randomForest(train$model_type_fac ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = train)
summary(scag_randomForest)
scag_randomForest$votes

test$preds <- predict(scag_randomForest, newdata = test)
mean(test$preds == test$model_type_fac)

failed <- test %>% filter(test$preds != test$model_type_fac)

failed %>% group_by(preds, model_type_fac) %>% select(preds, model_type_fac) %>% table()


```

```{r}
without_funnel <- data %>% filter(model != "funnel")
without_funnel$model_type_fac <- as.factor(without_funnel$model_type)
without_funnel$model_type_fac #now no funnel

train_ind <- sample(seq_len(nrow(without_funnel)), size = 20000)
train <- without_funnel[train_ind, ]
test <- without_funnel[-train_ind, ] 

scag_randomForest_wo <- randomForest(train$model_type_fac ~ scag_num_1+scag_num_2+scag_num_3+scag_num_4+scag_num_5+scag_num_6+scag_num_7+scag_num_8+scag_num_9, data = train, ntree = 400, mtry = 3)

test$preds <- predict(scag_randomForest_wo, newdata = test)

mean(test$preds == test$model_type_fac)

failed <- test %>% filter(test$preds != test$model_type_fac)

failed %>% group_by(preds, model_type_fac) %>% select(preds, model_type_fac) %>% table()
```


How to confuse it:
linear heteroskedascity
check medium vs strong correlation for linear trend